

export enum EditableProductActions {
    
    // PRODUCT INFORMATION
    IS_EDITING_INFORMATION = "IS_EDITING_INFORMATION",
    SET_PRODUCT_INFORMATION = "SET_PRODUCT_INFORMATION",
    IS_EDITING_PICTURE = "IS_EDITING_PICTURE",
    SET_PICTURE_URL = "SET_PICTURE_URL",
    
    // INGREDIENT
        // Add new ingredient
    ADD_NEW_INGREDIENT = "ADD_NEW_INGREDIENT",
    IS_ADDING_NEW_INGREDIENT = "IS_ADDING_NEW_INGREDIENT",
    // Edit Ingredient
    IS_EDITING_INGREDIENT_NAME = "IS_EDITING_INGREDIENT_NAME",
    EDIT_INGREDIENT_NAME = "EDIT_INGREDIENT_NAME",
    // Remove Ingredient
    REMOVE_INGREDIENT = "REMOVE_INGREDIENT",

    // OPTION TO INGREDIENT OPRIONS 
        // Add new option
    ADD_NEW_OPTION_TO_INGREDIENT = "ADD_NEW_OPTION_TO_INGREDIENT",
    IS_ADDING_NEW_OPTION_TO_INGREDIENT = "IS_ADDING_NEW_OPTION_TO_INGREDIENT",
        // Remove option
    REMOVE_OPTION_FROM_INGREDIENT = "REMOVE_OPTION_FROM_INGREDIENT",
    
    // IS_EDITING_NEW_INGREDIENT = "IS_EDITING_NEW_INGREDIENT",
    // SET_INGREDIENT_NAME = "SET_INGREDIENT_NAME",
    // IS_EDITING_INGREDIENT = "IS_EDITING_INGREDIENT",
}