

export enum EditableProductActions {
    // PRODUCT INFORMATION
    IS_EDITING_INFORMATION = "IS_EDITING_INFORMATION",
    SET_PRODUCT_INFORMATION = "SET_PRODUCT_INFORMATION",
    IS_EDITING_PICTURE ="IS_EDITING_PICTURE",
    SET_PICTURE_URL ="SET_PICTURE_URL",
    // INGREDIENT
    IS_EDITING_INGREDIENT_NAME ="IS_EDITING_INGREDIENT_NAME",
    SET_INGREDIENT_NAME ="SET_INGREDIENT_NAME",
    IS_EDITING_INGREDIENT_OPTION ="IS_EDITING_INGREDIENT_OPTION",
    SET_INGREDIENT_OPTION ="SET_INGREDIENT_OPTION",
}