

export enum EditableProductAction {
    ADD_PRODUCT_NAME = "ADD_PRODUCT_NAME",
    ADD_PRODUCT_DESCRIPTION = "ADD_PRODUCT_DESCRIPTION",
    ADD_PRODUCT_PRICE = "ADD_PRODUCT_PRICE",
    IS_EDITING_INFORMATION = "IS_EDITING_INFORMATION",
    IS_EDITING_PRICE ="IS_EDITING_PRICE",
}